name: On PR check

on: [pull_request]

jobs:
  code-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: |
          flutter pub get
          flutter pub run build_runner build

      - name: Check code is formatted
        run: |
          dart format lib --output=none --set-exit-if-changed
          dart format test --output=none --set-exit-if-changed

      - name: Analyze code
        run: flutter analyze --fatal-infos --fatal-warnings

      - name: Run tests and generate coverage report
        run: flutter test --coverage
